use crate::currency::Currency;
use crate::locale::Locale;
use std::fmt;

// Allows iterating over the Iso Enum
macro_rules! define_enum {
    ($Name:ident { $($Variant:ident),* $(,)* }) =>
    {
        #[derive(Debug)]
        pub enum $Name {
            $($Variant),*,
        }
        pub const ISO_CURRENCIES: &'static [$Name] = &[$($Name::$Variant),*];
    }
}

// Enum that represents every ISO Currency
define_enum!(Iso {
    AED,
    AFN,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    CAD,
    CDF,
    CHF,
    CLF,
    CLP,
    CNY,
    COP,
    CRC,
    CUC,
    CUP,
    CVE,
    CZK,
    DJF,
    DKK,
    DOP,
    DZD,
    EGP,
    ERN,
    ETB,
    EUR,
    FJD,
    FKP,
    GBP,
    GEL,
    GHS,
    GIP,
    GMD,
    GNF,
    GTQ,
    GYD,
    HKD,
    HNL,
    HRK,
    HTG,
    HUF,
    IDR,
    ILS,
    INR,
    IQD,
    IRR,
    ISK,
    JMD,
    JOD,
    JPY,
    KES,
    KGS,
    KHR,
    KMF,
    KPW,
    KRW,
    KWD,
    KYD,
    KZT,
    USD,
});

impl fmt::Display for Iso {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

/// Returns Currency given an Iso Enum.
pub fn from_enum(code: &Iso) -> Currency {
    use Iso::*;
    use Locale::*;

    match code {
        AED => Currency {
            exponent: 2,
            iso_alpha_code: "AED",
            iso_numeric_code: "784",
            locale: EnUs,
            minor_denomination: 25,
            name: "United Arab Emirates Dirham",
            symbol: "د.إ",
            symbol_first: false,
        },
        AFN => Currency {
            exponent: 2,
            iso_alpha_code: "AFN",
            iso_numeric_code: "971",
            locale: EnUs,
            minor_denomination: 100,
            name: "Afghan Afghani",
            symbol: "؋",
            symbol_first: false,
        },
        AMD => Currency {
            exponent: 2,
            iso_alpha_code: "AMD",
            iso_numeric_code: "051",
            locale: EnUs,
            minor_denomination: 10,
            name: "Armenian Dram",
            symbol: "դր.",
            symbol_first: false,
        },
        ANG => Currency {
            exponent: 2,
            iso_alpha_code: "ANG",
            iso_numeric_code: "532",
            locale: EnUs,
            minor_denomination: 1,
            name: "Netherlands Antillean Gulden",
            symbol: "ƒ",
            symbol_first: false,
        },
        AOA => Currency {
            exponent: 2,
            iso_alpha_code: "AOA",
            iso_numeric_code: "973",
            locale: EnUs,
            minor_denomination: 10,
            name: "Angolan Kwanza",
            symbol: "Kz",
            symbol_first: false,
        },
        ARS => Currency {
            exponent: 2,
            iso_alpha_code: "ARS",
            iso_numeric_code: "032",
            locale: EnEu,
            minor_denomination: 1,
            name: "Argentine Peso",
            symbol: "$",
            symbol_first: true,
        },
        AUD => Currency {
            exponent: 2,
            iso_alpha_code: "AUD",
            iso_numeric_code: "036",
            locale: EnUs,
            minor_denomination: 5,
            name: "Australian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        AWG => Currency {
            exponent: 2,
            iso_alpha_code: "AWG",
            iso_numeric_code: "533",
            locale: EnUs,
            minor_denomination: 5,
            name: "Aruban Florin",
            symbol: "ƒ",
            symbol_first: false,
        },
        AZN => Currency {
            exponent: 2,
            iso_alpha_code: "AZN",
            iso_numeric_code: "944",
            locale: EnUs,
            minor_denomination: 1,
            name: "Azerbaijani Manat",
            symbol: "₼",
            symbol_first: true,
        },
        BAM => Currency {
            exponent: 2,
            iso_alpha_code: "BAM",
            iso_numeric_code: "977",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bosnia and Herzegovina Convertible Mark",
            symbol: "KM",
            symbol_first: true,
        },
        BBD => Currency {
            exponent: 2,
            iso_alpha_code: "BBD",
            iso_numeric_code: "052",
            locale: EnUs,
            minor_denomination: 1,
            name: "Barbadian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BDT => Currency {
            exponent: 2,
            iso_alpha_code: "BDT",
            iso_numeric_code: "050",
            locale: EnIn,
            minor_denomination: 1,
            name: "Bangladeshi Taka",
            symbol: "৳",
            symbol_first: true,
        },

        BGN => Currency {
            exponent: 2,
            iso_alpha_code: "BGN",
            iso_numeric_code: "975",
            locale: EnIn,
            minor_denomination: 1,
            name: "Bulgarian Lev",
            symbol: "лв.",
            symbol_first: false,
        },
        BHD => Currency {
            exponent: 3,
            iso_alpha_code: "BHD",
            iso_numeric_code: "048",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bahraini Dinar",
            symbol: "ب.د",
            symbol_first: true,
        },
        BIF => Currency {
            exponent: 0,
            iso_alpha_code: "BIF",
            iso_numeric_code: "108",
            locale: EnUs,
            minor_denomination: 100,
            name: "Burundian Franc",
            symbol: "Fr",
            symbol_first: false,
        },

        BMD => Currency {
            exponent: 2,
            iso_alpha_code: "BMD",
            iso_numeric_code: "060",
            locale: EnUs,
            minor_denomination: 1,
            name: "Bermudian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BND => Currency {
            exponent: 2,
            iso_alpha_code: "BND",
            iso_numeric_code: "096",
            locale: EnUs,
            minor_denomination: 1,
            name: "Brunei Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BOB => Currency {
            exponent: 2,
            iso_alpha_code: "BOB",
            iso_numeric_code: "068",
            locale: EnUs,
            minor_denomination: 10,
            name: "Bolivian Boliviano",
            symbol: "Bs.",
            symbol_first: true,
        },
        BRL => Currency {
            exponent: 2,
            iso_alpha_code: "BOB",
            iso_numeric_code: "986",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bolivian Boliviano",
            symbol: "R$",
            symbol_first: true,
        },
        BSD => Currency {
            exponent: 2,
            iso_alpha_code: "BSD",
            iso_numeric_code: "044",
            locale: EnUs,
            minor_denomination: 1,
            name: "Bahamian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BTN => Currency {
            exponent: 2,
            iso_alpha_code: "BTN",
            iso_numeric_code: "064",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bhutanese Ngultrum",
            symbol: "Nu.",
            symbol_first: false,
        },
        BWP => Currency {
            exponent: 2,
            iso_alpha_code: "BWP",
            iso_numeric_code: "072",
            locale: EnUs,
            minor_denomination: 5,
            name: "Botswana Pula",
            symbol: "P",
            symbol_first: true,
        },
        BYN => Currency {
            exponent: 2,
            iso_alpha_code: "BYN",
            iso_numeric_code: "933",
            locale: EnBy,
            minor_denomination: 1,
            name: "Belarusian Ruble",
            symbol: "Br",
            symbol_first: false,
        },
        BYR => Currency {
            exponent: 0,
            iso_alpha_code: "BYR",
            iso_numeric_code: "974",
            locale: EnBy,
            minor_denomination: 100,
            name: "Belarusian Ruble",
            symbol: "Br",
            symbol_first: false,
        },
        BZD => Currency {
            exponent: 2,
            iso_alpha_code: "BZD",
            iso_numeric_code: "084",
            locale: EnUs,
            minor_denomination: 1,
            name: "Belize Dollar",
            symbol: "$",
            symbol_first: true,
        },
        CAD => Currency {
            exponent: 2,
            iso_alpha_code: "CAD",
            iso_numeric_code: "124",
            locale: EnUs,
            minor_denomination: 5,
            name: "Canadian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        CDF => Currency {
            exponent: 2,
            iso_alpha_code: "CDF",
            iso_numeric_code: "976",
            locale: EnUs,
            minor_denomination: 1,
            name: "Congolese Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        CHF => Currency {
            exponent: 2,
            iso_alpha_code: "CHF",
            iso_numeric_code: "756",
            locale: EnUs,
            minor_denomination: 5,
            name: "Swiss Franc",
            symbol: "Fr",
            symbol_first: true,
        },
        CLF => Currency {
            exponent: 4,
            iso_alpha_code: "CLF",
            iso_numeric_code: "990",
            locale: EnEu,
            minor_denomination: 5,
            name: "Unidad de Fomento",
            symbol: "UF",
            symbol_first: true,
        },
        CLP => Currency {
            exponent: 0,
            iso_alpha_code: "CLP",
            iso_numeric_code: "152",
            locale: EnEu,
            minor_denomination: 1,
            name: "Chilean Peso",
            symbol: "$",
            symbol_first: true,
        },
        CNY => Currency {
            exponent: 2,
            iso_alpha_code: "CNY",
            iso_numeric_code: "156",
            locale: EnUs,
            minor_denomination: 1,
            name: "Chinese Renminbi Yuan",
            symbol: "¥",
            symbol_first: true,
        },
        COP => Currency {
            exponent: 2,
            iso_alpha_code: "COP",
            iso_numeric_code: "170",
            locale: EnEu,
            minor_denomination: 20,
            name: "Colombian Peso",
            symbol: "$",
            symbol_first: true,
        },
        CRC => Currency {
            exponent: 2,
            iso_alpha_code: "CRC",
            iso_numeric_code: "188",
            locale: EnEu,
            minor_denomination: 500, // TODO - Investigate
            name: "Costa Rican Colón",
            symbol: "₡",
            symbol_first: true,
        },
        CUC => Currency {
            exponent: 2,
            iso_alpha_code: "CUC",
            iso_numeric_code: "931",
            locale: EnUs,
            minor_denomination: 1,
            name: "Cuban Convertible Peso",
            symbol: "$",
            symbol_first: false,
        },
        CUP => Currency {
            exponent: 2,
            iso_alpha_code: "CUP",
            iso_numeric_code: "192",
            locale: EnUs,
            minor_denomination: 1,
            name: "Cuban Peso",
            symbol: "$",
            symbol_first: true,
        },
        CVE => Currency {
            exponent: 2,
            iso_alpha_code: "CVE",
            iso_numeric_code: "132",
            locale: EnUs,
            minor_denomination: 100,
            name: "Cape Verdean Escudo",
            symbol: "$",
            symbol_first: false,
        },
        CZK => Currency {
            exponent: 2,
            iso_alpha_code: "CZK",
            iso_numeric_code: "132",
            locale: EnBy,
            minor_denomination: 100,
            name: "Czech Koruna",
            symbol: "Kč",
            symbol_first: false,
        },
        DJF => Currency {
            exponent: 0,
            iso_alpha_code: "DJF",
            iso_numeric_code: "262",
            locale: EnUs,
            minor_denomination: 100,
            name: "Djiboutian Franc",
            symbol: "Fdj",
            symbol_first: false,
        },
        DKK => Currency {
            exponent: 2,
            iso_alpha_code: "DKK",
            iso_numeric_code: "208",
            locale: EnEu,
            minor_denomination: 50,
            name: "Danish Krone",
            symbol: "kr.",
            symbol_first: false,
        },
        DOP => Currency {
            exponent: 2,
            iso_alpha_code: "DOP",
            iso_numeric_code: "214",
            locale: EnUs,
            minor_denomination: 100,
            name: "Dominican Peso",
            symbol: "$",
            symbol_first: true,
        },
        DZD => Currency {
            exponent: 2,
            iso_alpha_code: "DZD",
            iso_numeric_code: "012",
            locale: EnUs,
            minor_denomination: 100,
            name: "Algerian Dinar",
            symbol: "د.ج",
            symbol_first: false,
        },
        EGP => Currency {
            exponent: 2,
            iso_alpha_code: "EGP",
            iso_numeric_code: "818",
            locale: EnUs,
            minor_denomination: 25,
            name: "Egyptian Pound",
            symbol: "ج.م",
            symbol_first: true,
        },
        ERN => Currency {
            exponent: 2,
            iso_alpha_code: "ERN",
            iso_numeric_code: "232",
            locale: EnUs,
            minor_denomination: 1,
            name: "Eritrean Nakfa",
            symbol: "Nfk",
            symbol_first: false,
        },
        ETB => Currency {
            exponent: 2,
            iso_alpha_code: "ETB",
            iso_numeric_code: "230",
            locale: EnUs,
            minor_denomination: 1,
            name: "Ethiopian Birr",
            symbol: "Br",
            symbol_first: false,
        },
        EUR => Currency {
            exponent: 2,
            iso_alpha_code: "EUR",
            iso_numeric_code: "978",
            locale: EnEu,
            minor_denomination: 1,
            name: "Euro",
            symbol: "€",
            symbol_first: true,
        },
        FJD => Currency {
            exponent: 2,
            iso_alpha_code: "FJD",
            iso_numeric_code: "242",
            locale: EnEu,
            minor_denomination: 5,
            name: "Fijian Dollar",
            symbol: "$",
            symbol_first: false,
        },
        FKP => Currency {
            exponent: 2,
            iso_alpha_code: "FKP",
            iso_numeric_code: "238",
            locale: EnEu,
            minor_denomination: 1,
            name: "Falkland Pound",
            symbol: "£",
            symbol_first: false,
        },
        GBP => Currency {
            exponent: 2,
            iso_alpha_code: "GBP",
            iso_numeric_code: "826",
            locale: EnUs,
            minor_denomination: 1,
            name: "British Pound",
            symbol: "£",
            symbol_first: true,
        },
        GEL => Currency {
            exponent: 2,
            iso_alpha_code: "GEL",
            iso_numeric_code: "981",
            locale: EnUs,
            minor_denomination: 1,
            name: "Georgian Lari",
            symbol: "ლ",
            symbol_first: false,
        },
        GHS => Currency {
            exponent: 2,
            iso_alpha_code: "GHS",
            iso_numeric_code: "936",
            locale: EnUs,
            minor_denomination: 1,
            name: "Ghanaian Cedi",
            symbol: "₵",
            symbol_first: true,
        },
        GIP => Currency {
            exponent: 2,
            iso_alpha_code: "GIP",
            iso_numeric_code: "292",
            locale: EnUs,
            minor_denomination: 1,
            name: "Gibraltar Pound",
            symbol: "£",
            symbol_first: true,
        },
        GMD => Currency {
            exponent: 2,
            iso_alpha_code: "GMD",
            iso_numeric_code: "270",
            locale: EnUs,
            minor_denomination: 1,
            name: "Gambian Dalasi",
            symbol: "D",
            symbol_first: false,
        },
        GNF => Currency {
            exponent: 0,
            iso_alpha_code: "GNF",
            iso_numeric_code: "324",
            locale: EnUs,
            minor_denomination: 100,
            name: "Guinean Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        GTQ => Currency {
            exponent: 2,
            iso_alpha_code: "GTQ",
            iso_numeric_code: "320",
            locale: EnUs,
            minor_denomination: 1,
            name: "Guatemalan Quetzal",
            symbol: "Q",
            symbol_first: true,
        },
        GYD => Currency {
            exponent: 2,
            iso_alpha_code: "GYD",
            iso_numeric_code: "328",
            locale: EnUs,
            minor_denomination: 100,
            name: "Guyanese Dollar",
            symbol: "$",
            symbol_first: false,
        },
        HKD => Currency {
            exponent: 2,
            iso_alpha_code: "HKD",
            iso_numeric_code: "344",
            locale: EnUs,
            minor_denomination: 10,
            name: "Hong Kong Dollar",
            symbol: "$",
            symbol_first: true,
        },
        HNL => Currency {
            exponent: 2,
            iso_alpha_code: "HNL",
            iso_numeric_code: "340",
            locale: EnUs,
            minor_denomination: 5,
            name: "Honduran Lempira",
            symbol: "L",
            symbol_first: true,
        },
        HRK => Currency {
            exponent: 2,
            iso_alpha_code: "HRK",
            iso_numeric_code: "191",
            locale: EnEu,
            minor_denomination: 1,
            name: "Croatian Kuna",
            symbol: "kn",
            symbol_first: false,
        },
        HTG => Currency {
            exponent: 2,
            iso_alpha_code: "HTG",
            iso_numeric_code: "332",
            locale: EnUs,
            minor_denomination: 5,
            name: "Haitian Gourde",
            symbol: "G",
            symbol_first: false,
        },
        HUF => Currency {
            exponent: 0,
            iso_alpha_code: "HTG",
            iso_numeric_code: "348",
            locale: EnBy,
            minor_denomination: 5,
            name: "Hungarian Forint",
            symbol: "Ft",
            symbol_first: false,
        },
        IDR => Currency {
            exponent: 2,
            iso_alpha_code: "IDR",
            iso_numeric_code: "360",
            locale: EnUs,
            minor_denomination: 5000,
            name: "Indonesian Rupiah",
            symbol: "Rp",
            symbol_first: true,
        },
        ILS => Currency {
            exponent: 2,
            iso_alpha_code: "ILS",
            iso_numeric_code: "376",
            locale: EnUs,
            minor_denomination: 10,
            name: "Israeli New Sheqel",
            symbol: "₪",
            symbol_first: true,
        },
        INR => Currency {
            exponent: 2,
            iso_alpha_code: "INR",
            iso_numeric_code: "356",
            locale: EnIn,
            minor_denomination: 50,
            name: "Indian Rupee",
            symbol: "₹",
            symbol_first: true,
        },
        IQD => Currency {
            exponent: 3,
            iso_alpha_code: "IQD",
            iso_numeric_code: "368",
            locale: EnUs,
            minor_denomination: 50000,
            name: "Iraqi Dinar",
            symbol: "ع.د",
            symbol_first: false,
        },
        IRR => Currency {
            exponent: 2,
            iso_alpha_code: "IRR",
            iso_numeric_code: "364",
            locale: EnUs,
            minor_denomination: 5000,
            name: "Iranian Rial",
            symbol: "﷼",
            symbol_first: true,
        },
        ISK => Currency {
            exponent: 0,
            iso_alpha_code: "ISK",
            iso_numeric_code: "352",
            locale: EnEu,
            minor_denomination: 1,
            name: "Icelandic Króna",
            symbol: "kr",
            symbol_first: true,
        },
        JMD => Currency {
            exponent: 2,
            iso_alpha_code: "JMD",
            iso_numeric_code: "388",
            locale: EnUs,
            minor_denomination: 1,
            name: "Jamaican Dollar",
            symbol: "$",
            symbol_first: true,
        },
        JOD => Currency {
            exponent: 3,
            iso_alpha_code: "JOD",
            iso_numeric_code: "400",
            locale: EnUs,
            minor_denomination: 5,
            name: "Jordanian Dinar",
            symbol: "د.ا",
            symbol_first: true,
        },
        JPY => Currency {
            exponent: 0,
            iso_alpha_code: "JPY",
            iso_numeric_code: "392",
            locale: EnUs,
            minor_denomination: 1,
            name: "Japanese Yen",
            symbol: "¥",
            symbol_first: true,
        },
        KES => Currency {
            exponent: 2,
            iso_alpha_code: "KES",
            iso_numeric_code: "404",
            locale: EnUs,
            minor_denomination: 50,
            name: "Kenyan Shilling",
            symbol: "KSh",
            symbol_first: true,
        },
        KGS => Currency {
            exponent: 2,
            iso_alpha_code: "KGS",
            iso_numeric_code: "417",
            locale: EnUs,
            minor_denomination: 1,
            name: "Kyrgyzstani Som",
            symbol: "som",
            symbol_first: false,
        },
        KHR => Currency {
            exponent: 2,
            iso_alpha_code: "KHR",
            iso_numeric_code: "116",
            locale: EnUs,
            minor_denomination: 5000,
            name: "Cambodian Riel",
            symbol: "៛",
            symbol_first: false,
        },
        KMF => Currency {
            exponent: 0,
            iso_alpha_code: "KMF",
            iso_numeric_code: "174",
            locale: EnUs,
            minor_denomination: 100,
            name: "Comorian Franc",
            symbol: "Fr",
            symbol_first: false,
        },
        KPW => Currency {
            exponent: 2,
            iso_alpha_code: "KPW",
            iso_numeric_code: "408",
            locale: EnUs,
            minor_denomination: 1,
            name: "North Korean Won",
            symbol: "₩",
            symbol_first: false,
        },
        KRW => Currency {
            exponent: 0,
            iso_alpha_code: "KRW",
            iso_numeric_code: "410",
            locale: EnUs,
            minor_denomination: 1,
            name: "South Korean Won",
            symbol: "₩",
            symbol_first: true,
        },
        KWD => Currency {
            exponent: 3,
            iso_alpha_code: "KWD",
            iso_numeric_code: "414",
            locale: EnUs,
            minor_denomination: 5,
            name: "Kuwaiti Dinar",
            symbol: "د.ك",
            symbol_first: true,
        },
        KYD => Currency {
            exponent: 2,
            iso_alpha_code: "KYD",
            iso_numeric_code: "136",
            locale: EnUs,
            minor_denomination: 1,
            name: "Cayman Islands Dollar",
            symbol: "$",
            symbol_first: true,
        },
        KZT => Currency {
            exponent: 2,
            iso_alpha_code: "KZT",
            iso_numeric_code: "398",
            locale: EnUs,
            minor_denomination: 100,
            name: "Kazakhstani Tenge",
            symbol: "₸",
            symbol_first: false,
        },
        // Start here
        USD => Currency {
            exponent: 2,
            iso_alpha_code: "USD",
            iso_numeric_code: "840",
            locale: EnUs,
            minor_denomination: 1,
            name: "United States Dollar",
            symbol: "$",
            symbol_first: true,
        },
    }
}
