use crate::currency::Currency;
use crate::locale::Locale;
use std::fmt;

// Allows iterating over the Iso Enum
macro_rules! define_enum {
    ($Name:ident { $($Variant:ident),* $(,)* }) =>
    {
        #[derive(Debug)]
        pub enum $Name {
            $($Variant),*,
        }
        pub const ISO_CURRENCIES: &'static [$Name] = &[$($Name::$Variant),*];
    }
}

// Enum that represents every ISO Currency
define_enum!(Iso {
    AED,
    AFN,
    AMD,
    ANG,
    AOA,
    ARS,
    AUD,
    AWG,
    AZN,
    BAM,
    BBD,
    BDT,
    BGN,
    BHD,
    BIF,
    BMD,
    BND,
    BOB,
    BRL,
    BSD,
    BTN,
    BWP,
    BYN,
    BYR,
    BZD,
    EUR,
    GBP,
    INR,
    USD,
});

impl fmt::Display for Iso {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}

/// Returns Currency given an Iso Enum.
pub fn from_enum(code: &Iso) -> Currency {
    use Iso::*;
    use Locale::*;

    match code {
        AED => Currency {
            exponent: 2,
            iso_alpha_code: "AED",
            iso_numeric_code: "784",
            locale: EnUs,
            minor_denomination: 25,
            name: "United Arab Emirates Dirham",
            symbol: "د.إ",
            symbol_first: false,
        },
        AFN => Currency {
            exponent: 2,
            iso_alpha_code: "AFN",
            iso_numeric_code: "971",
            locale: EnUs,
            minor_denomination: 100,
            name: "Afghan Afghani",
            symbol: "؋",
            symbol_first: false,
        },
        AMD => Currency {
            exponent: 2,
            iso_alpha_code: "AMD",
            iso_numeric_code: "051",
            locale: EnUs,
            minor_denomination: 10,
            name: "Armenian Dram",
            symbol: "դր.",
            symbol_first: false,
        },
        ANG => Currency {
            exponent: 2,
            iso_alpha_code: "ANG",
            iso_numeric_code: "532",
            locale: EnUs,
            minor_denomination: 1,
            name: "Netherlands Antillean Gulden",
            symbol: "ƒ",
            symbol_first: false,
        },
        AOA => Currency {
            exponent: 2,
            iso_alpha_code: "AOA",
            iso_numeric_code: "973",
            locale: EnUs,
            minor_denomination: 10,
            name: "Angolan Kwanza",
            symbol: "Kz",
            symbol_first: false,
        },
        ARS => Currency {
            exponent: 2,
            iso_alpha_code: "ARS",
            iso_numeric_code: "032",
            locale: EnEu,
            minor_denomination: 1,
            name: "Argentine Peso",
            symbol: "$",
            symbol_first: true,
        },
        AUD => Currency {
            exponent: 2,
            iso_alpha_code: "AUD",
            iso_numeric_code: "036",
            locale: EnUs,
            minor_denomination: 5,
            name: "Australian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        AWG => Currency {
            exponent: 2,
            iso_alpha_code: "AWG",
            iso_numeric_code: "533",
            locale: EnUs,
            minor_denomination: 5,
            name: "Aruban Florin",
            symbol: "ƒ",
            symbol_first: false,
        },
        AZN => Currency {
            exponent: 2,
            iso_alpha_code: "AZN",
            iso_numeric_code: "944",
            locale: EnUs,
            minor_denomination: 1,
            name: "Azerbaijani Manat",
            symbol: "₼",
            symbol_first: true,
        },
        BAM => Currency {
            exponent: 2,
            iso_alpha_code: "BAM",
            iso_numeric_code: "977",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bosnia and Herzegovina Convertible Mark",
            symbol: "KM",
            symbol_first: true,
        },
        BBD => Currency {
            exponent: 2,
            iso_alpha_code: "BBD",
            iso_numeric_code: "052",
            locale: EnUs,
            minor_denomination: 1,
            name: "Barbadian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BDT => Currency {
            exponent: 2,
            iso_alpha_code: "BDT",
            iso_numeric_code: "050",
            locale: EnIn,
            minor_denomination: 1,
            name: "Bangladeshi Taka",
            symbol: "৳",
            symbol_first: true,
        },

        BGN => Currency {
            exponent: 2,
            iso_alpha_code: "BGN",
            iso_numeric_code: "975",
            locale: EnIn,
            minor_denomination: 1,
            name: "Bulgarian Lev",
            symbol: "лв.",
            symbol_first: false,
        },
        BHD => Currency {
            exponent: 3,
            iso_alpha_code: "BHD",
            iso_numeric_code: "048",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bahraini Dinar",
            symbol: "ب.د",
            symbol_first: true,
        },
        BIF => Currency {
            exponent: 0,
            iso_alpha_code: "BIF",
            iso_numeric_code: "108",
            locale: EnUs,
            minor_denomination: 100,
            name: "Burundian Franc",
            symbol: "Fr",
            symbol_first: false,
        },

        BMD => Currency {
            exponent: 2,
            iso_alpha_code: "BMD",
            iso_numeric_code: "060",
            locale: EnUs,
            minor_denomination: 1,
            name: "Bermudian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BND => Currency {
            exponent: 2,
            iso_alpha_code: "BND",
            iso_numeric_code: "096",
            locale: EnUs,
            minor_denomination: 1,
            name: "Brunei Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BOB => Currency {
            exponent: 2,
            iso_alpha_code: "BOB",
            iso_numeric_code: "068",
            locale: EnUs,
            minor_denomination: 10,
            name: "Bolivian Boliviano",
            symbol: "Bs.",
            symbol_first: true,
        },
        BRL => Currency {
            exponent: 2,
            iso_alpha_code: "BOB",
            iso_numeric_code: "986",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bolivian Boliviano",
            symbol: "R$",
            symbol_first: true,
        },
        BSD => Currency {
            exponent: 2,
            iso_alpha_code: "BSD",
            iso_numeric_code: "044",
            locale: EnUs,
            minor_denomination: 1,
            name: "Bahamian Dollar",
            symbol: "$",
            symbol_first: true,
        },
        BTN => Currency {
            exponent: 2,
            iso_alpha_code: "BTN",
            iso_numeric_code: "064",
            locale: EnUs,
            minor_denomination: 5,
            name: "Bhutanese Ngultrum",
            symbol: "Nu.",
            symbol_first: false,
        },
        BWP => Currency {
            exponent: 2,
            iso_alpha_code: "BWP",
            iso_numeric_code: "072",
            locale: EnUs,
            minor_denomination: 5,
            name: "Botswana Pula",
            symbol: "P",
            symbol_first: true,
        },
        BYN => Currency {
            exponent: 2,
            iso_alpha_code: "BYN",
            iso_numeric_code: "933",
            locale: EnBy,
            minor_denomination: 1,
            name: "Belarusian Ruble",
            symbol: "Br",
            symbol_first: false,
        },
        BYR => Currency {
            exponent: 0,
            iso_alpha_code: "BYR",
            iso_numeric_code: "974",
            locale: EnBy,
            minor_denomination: 100,
            name: "Belarusian Ruble",
            symbol: "Br",
            symbol_first: false,
        },
        BZD => Currency {
            exponent: 2,
            iso_alpha_code: "BZD",
            iso_numeric_code: "084",
            locale: EnUs,
            minor_denomination: 1,
            name: "Belize Dollar",
            symbol: "$",
            symbol_first: true,
        },
        // Start here
        EUR => Currency {
            exponent: 2,
            iso_alpha_code: "EUR",
            iso_numeric_code: "978",
            locale: EnEu,
            minor_denomination: 1,
            name: "Euro",
            symbol: "€",
            symbol_first: true,
        },
        GBP => Currency {
            exponent: 2,
            iso_alpha_code: "GBP",
            iso_numeric_code: "826",
            locale: EnUs,
            minor_denomination: 1,
            name: "British Pound",
            symbol: "£",
            symbol_first: true,
        },
        INR => Currency {
            exponent: 2,
            iso_alpha_code: "INR",
            iso_numeric_code: "356",
            locale: EnIn,
            minor_denomination: 50,
            name: "Indian Rupee",
            symbol: "₹",
            symbol_first: true,
        },
        USD => Currency {
            exponent: 2,
            iso_alpha_code: "USD",
            iso_numeric_code: "840",
            locale: EnUs,
            minor_denomination: 1,
            name: "United States Dollar",
            symbol: "$",
            symbol_first: true,
        },
    }
}
